In [29]:
import numpy as np

# a + 2b + 3c + 4d = 30

n = 6
# 1. Pembentukan chromosome
chromosome = np.random.randint(0, 30,(n,4))

# 2. Inisialisasi
print("Chromosome : ")
print("")
print(chromosome)

Chromosome : 

[[16 24  8  1]
 [ 1  1 21 25]
 [28 13 26  7]
 [ 0  8  6  7]
 [ 0 29 25 16]
 [25 27 21 11]]


In [35]:
generasi = 0
while generasi < 200 :

  print("")
  print("")
  print("----------------------------------------------------------------------------------------------------")
  print("Generasi -", generasi + 1)
  print("----------------------------------------------------------------------------------------------------")


  # 3. Evaluasi Chromosome
  
    #Fungsi Objektif
  fungsi_objektif = abs(chromosome[:,0] + 2*chromosome[:,1] + 3*chromosome[:,2] + 4*chromosome[:,3] - 30)
  print("Fungsi Objektif : ",fungsi_objektif)

    #Rata-rata dari fungsi objektif
  print("Rata2 Fungsi Objektif :",np.average(fungsi_objektif))


  # 4. Seleksi Chromosome
  fitness = 1/(1+fungsi_objektif)
  print("Fitness :",fitness)

    #total fitness
  total = fitness.sum()
  print("Total Fitness :",total)

    #Probabilitas
  P = fitness/total
  print("Probabilitas :", P)

    #kumulatif probabilitas
  C = np.cumsum(P)
  print("Kumulatif Probabilitas :", C)

    #membangkitkan bilangan acak R dalam range 0-1
  Acak = np.random.random((chromosome.shape[0]))
  print("R :", Acak)

    # Membuat Chromosome baru untuk hasil Roulet Wheel
  chromosome2 = np.zeros((chromosome.shape[0],4))

    # Proses Roulet Wheel
  for i in range(Acak.shape[0]):
    for j in range(chromosome.shape[0]):
      if Acak[i] < C[j]:
        chromosome2[i,:] = chromosome[j,:]
        break

  chromosome = chromosome2
  print("Chromosome Setelah Seleksi :")
  print(chromosome)      

  
  # 5. Crossover / Persilangan

    # crossover probability adalah sebesar 25%
  pc = 0.25

    # bangkitkan bilangan acak R sebanyak jumlah populasi
  R = [np.random.random() for i in range(n)]
  print("Nilai Random ",R)

    # Chromosome ke k akan dipilih sebagai induk jika R[k] < ρc
  flag = Acak < pc
  print("NIlai Flag ",flag)

    # menentukan posisi crossover
  cross_chromosome = chromosome [[(i == True) for i in flag]]
  print("Cross Chromosome : ")
  print(cross_chromosome)
  len_cross_chrom = len(cross_chromosome)

    # bilangan acak dibangkitkan adalah 1-3
  cross_values = np.random.randint(1,3,len_cross_chrom)
  print("C :",cross_values)

    # membuat offspring hasil perilangan chromosome
  offspring = np.zeros(cross_chromosome.shape)

    # membuat offspring sebanyak cross_chromosome
  for i in range(cross_chromosome.shape[0]):
    offspring[i,:] = cross_chromosome[i,:]

    # proses persilangan
  if len_cross_chrom == 1:
    cross_chromosome = cross_chromosome
  else :
    for i in range(len_cross_chrom):
      c_val = cross_values[i]
      if i == len_cross_chrom - 1 :
        cross_chromosome[i, c_val:] = offspring[0,c_val:]
      else :
        cross_chromosome[i, c_val:] = offspring[i+1,c_val:]

  print("Crossover Chromosome :")
  print(cross_chromosome)

  # proses replacement ke variabel chromosome
  index_chromosome = 0
  index_chromosomebaru = 0
  for i in flag:
    if i == True:
      chromosome[index_chromosome,:] = cross_chromosome[index_chromosomebaru,:]
      index_chromosomebaru = index_chromosomebaru + 1
      index_chromosome = index_chromosome + 1
  print("Chromosome Baru :")
  print(chromosome)

  # 6. Mutasi
  a,b = chromosome.shape[0],chromosome.shape[1]
  total_gen = a*b
  print("Total Gen :",total_gen)

    # mutasi rate (pm)
  pm = 0.1
  jumlah_mutasi = int(np.round(pm * total_gen))
  print("Jumlah Mutasi :", jumlah_mutasi)

    # membangkitkan bilangan acak
  gen_num = np.random.randint(0,total_gen - 1, jumlah_mutasi)
  print(" Generate Blangan Acak :", gen_num)

  print("Chromosome Sebelum dimutasi :", chromosome)

    # nilai gen pada posisi tersebut kita ganti dengan bilangan acak 0-30
  Ganti_angka = np.random.randint(0,30, jumlah_mutasi)
  print("Gen yang diganti :",Ganti_angka)

  for i in range(jumlah_mutasi):
    a = gen_num[i]
    baris = a//4
    kolom = a%4
    chromosome[baris, kolom] = Ganti_angka[i]

  print("Chromosome Setelah dimutasi :", chromosome)
  generasi = generasi + 1



Streaming output truncated to the last 5000 lines.
 [13.  0.  3.  2.]
 [13.  0.  3.  2.]]
Gen yang diganti : [19  1]
Chromosome Setelah dimutasi : [[13.  0.  3.  2.]
 [13.  0.  1. 19.]
 [13.  0.  3.  2.]
 [13.  0.  3.  2.]
 [13.  0.  3.  2.]
 [13.  0.  3.  2.]]


----------------------------------------------------------------------------------------------------
Generasi - 102
----------------------------------------------------------------------------------------------------
Fungsi Objektif :  [ 0. 62.  0.  0.  0.  0.]
Rata2 Fungsi Objektif : 10.333333333333334
Fitness : [1.         0.01587302 1.         1.         1.         1.        ]
Total Fitness : 5.015873015873016
Probabilitas : [0.19936709 0.00316456 0.19936709 0.19936709 0.19936709 0.19936709]
Kumulatif Probabilitas : [0.19936709 0.20253165 0.40189873 0.60126582 0.80063291 1.        ]
R : [0.61516667 0.79084489 0.28814592 0.1530222  0.49428969 0.81547838]
Chromosome Setelah Seleksi :
[[13.  0.  3.  2.]
 [13.  0.  3.  2.]
 [13